---
    # This playbook is to perform MySQL installations.

  - name: install mariadb-server
    yum: name={{ packages }} state=present
    vars:
      packages:
        - mariadb
        - mariadb-server

  - name: Install MySQL python for CentOS 7
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
    yum: name=MySQL-python state=present

  - name: Install MySQL python for CentOS 8
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"
    yum: name=python3-PyMySQL state=present

  - name: start mysqld
    systemd:
      name: mariadb
      state: started
      enabled: true

  - name: open port {{ mysql_port }}
    firewalld:
      port: '{{ mysql_port }}/tcp'
      permanent: true
      state: enabled
      immediate: yes
    notify: restart firewalld

  - name: check if root password for mariadb is set
    shell: >
        mysqladmin -u root status
    changed_when: false
    failed_when: false
    register: root_pwd_check

  - name: set mariadb root password for first time
    mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host_all: yes
        state: present
    when: root_pwd_check.rc == 0

  - name: flush privileges
    command: 'mysql -ne "FLUSH PRIVILEGES" -uroot -p"{{ mysql_root_password }}"'
    changed_when: False

  - name: Remove anonymous users
    mysql_user:
      name: ''
      host_all: yes
      login_user: root
      login_password: "{{ mysql_root_password }}"
      state: absent

  - name: Remove test database and access to it
    mysql_db:
      name: test
      login_user: root
      login_password: "{{ mysql_root_password }}"
      state: absent

  - name: Disallow root login remotely
    command: mysql -ne "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')" -uroot -p"{{ mysql_root_password }}"
    changed_when: False

  - name: flush privileges
    command: 'mysql -ne "FLUSH PRIVILEGES" -uroot -p"{{ mysql_root_password }}"'
    changed_when: False