---
    # This playbook is to perform MySQL installations.

    - rpm_key:
        state: present
        key: http://repo.mysql.com/RPM-GPG-KEY-mysql
    
    - name: Install MySQL Software Repo
      yum:
        name: http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm
        state: present
    
    - name: Install MySQL Database
      yum: name=mysql-server state=present
    
    - name: Start & Enable MySQL Server to start on boot
      service: name=mysqld state=started enabled=yes

    - shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    -  set_fact:
        mysql_root_pw: "{{ result.stdout }}"

    - name: Copy .my.cnf file with root password credentials
      template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
    
    - name: Set the root password for MySQL Database
      command: "mysql -e \"SET PASSWORD = '{{ masterpassword }}';\"
        --connect-expired-password -uroot -p'{{ mysql_root_pw }}'
        && touch /root/mysql_pass_changed"
      args: 
        creates: /root/mysql_pass_changed
    -  set_fact:
        mysql_root_pw: "{{ masterpassword }}"
    
    - name: Create the database for website
      mysql_db: name={{ dbname }} state=present
    
    - name: Create the Application user for the database
      mysql_user: name={{ dbuser }} password={{ upassword }} priv='*.*:ALL' host='%' state=present
        
    - name: Enable the firewall port for MySQL
      firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes