---
    # This playbook is to perform MySQL installations.
        
    - name: Install MySQL Software Repo
      yum:
        name: mariadb-server
        state: present
    
    - name: Install MySQL Database
      yum: name=mysql-server state=present

    - name: Install MySQL python for CentOS 7
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
      yum: name=MySQL-python state=present

    - name: Install MySQL python for CentOS 8
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"
      yum: name=python3-PyMySQL state=present

    - name: Start & Enable MySQL Server to start on boot
      service: name=mysqld state=started enabled=yes

    - shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    -  set_fact:
        mysql_root_pw: "{{ result.stdout }}"

    # - name: Copy .my.cnf file with root password credentials
    #   template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0400
    
    # - name: Set the root password for MySQL Database
    #   shell: mysql -u root --connect-expired-password --execute="SET PASSWORD = '{{ masterpassword }}';" && touch /root/mysql_pass_changed
    #   args: 
    #     creates: /root/mysql_pass_changed

    # - set_fact:
    #     mysql_root_pw: "{{ masterpassword }}"

    # - name: Copy .my.cnf file with root password credentials
    #   template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0400
    
    # - name: Create the database for website
    #   mysql_db: name={{ dbname }} state=present
    
    # - name: Create the Application user for the database
    #   mysql_user: name={{ dbuser }} password={{ upassword }} priv='*.*:ALL' host='%' state=present
        
    # - name: Enable the firewall port for MySQL
    #   firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes